### ISSUE TITLE
wrong!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by LappySheep** [fmleo/weo#3]
it is WHEN not WHERE 

angy

**Comment by metalcupcake5** [comment]
:nerd_face: akshually it is showing where the 727 is so it is correct

**Comment by fmleo** [comment]
ermm its where???
because its used on a specific message :+1:

**Comment by LappySheep** [comment]
this is true my bad i apologise for the inconvenience for the message that you had to read last week this is very true and real and real true and true real and real and true and real
